
## org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

##  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  resources.add-mappings: true
  profiles:
    active: dev

mybatis:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:config/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  rowBoundsWithCount: true
  offsetAsPageNum: true



mybatis-plus:
  typeEnumsPackage: io.diamondnetwork.model.enums
